require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'OrderArt' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  pod 'react-native-notification-sounds', :path => '../node_modules/react-native-notification-sounds'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  # pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios'

  
  pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'RNZohodeskPortalSdk', :path => '../node_modules/react-native-zohodesk-portal-sdk/ios'

  pod 'react-native-keep-awake', :path => '../node_modules/@sayem314/react-native-keep-awake'

  target 'OrderArtTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'OrderArt-tvOS' do
  # Pods for OrderArt-tvOS

  target 'OrderArt-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
